### ISSUE TITLE
Submodule Broken and Prompt Issue

### ISSUE THREAD

**Issue by michaelsharpe** [vorple/vorple#43]
Hey!

Thanks for such an awesome project.  I am trying to compile it right now, for reasons I'll also mention, and am having trouble.

It looks like the Haven submodule was updated to a branch that doesn't exist anymore on the Haven repo.  Specifically branch 9f5b7035a82ba0c4bbeefe19059d8da91886194c.  I assume it is needed because the current haven branch throws some not found errors when bundling through webpack.

Related to this, it seems that there is no "compile" script when I run `npm run compile`, and as such the two Git and Glulx requirements don't build.  I am not that familiar with emscripten so I am not sure what to do to make these dependencies compile.

I spun down this rabbit hole because I am trying to get save functionality to work on my site/project.  It was obviously running an older version, and so my players can't save.  When I tested on the latest version via a new Inform 7 story with the latest Vorple installed, it worked fine.

However, the one thing that was causing me some issues when I updated was that the prompt seemed to have moved.  It is now on the line above the the input.  Previously, it populated inside the inputs label (see attached screenshot).  This throws off the "terminal effect" my game is going for, so I need to correct it before I update to fix the save functionality.

Current prompt styling:
<img width="772" alt="Screen Shot 2019-10-26 at 6 47 45 PM" src="https://user-images.githubusercontent.com/2397603/67626958-6d210300-f821-11e9-9907-2adde616fa88.png">

Html of the `>` icon as part of the previous text, rather than as the label.
<img width="548" alt="Screen Shot 2019-10-26 at 6 49 50 PM" src="https://user-images.githubusercontent.com/2397603/67626959-6d210300-f821-11e9-8e79-1f76a2506113.png">

Result:
<img width="799" alt="Screen Shot 2019-10-26 at 6 49 05 PM" src="https://user-images.githubusercontent.com/2397603/67626961-6d210300-f821-11e9-9cf4-d979feddf30c.png">

I was trying to dive into the source code to se if I could fix this, which led me down trying to compile the project, and the issues I faced with that.

Any help would be greatly appreciated.

Thanks again!

==== edit ====

Oh, I also noticed in the console it was throwing this error a few times, and couldn't for the life of me track down in the code where this `Module` gets loaded in. I assume it is some global variable from a dependency that isn't explicitly mentioned anywhere?

<img width="576" alt="Screen Shot 2019-10-26 at 7 01 37 PM" src="https://user-images.githubusercontent.com/2397603/67627070-3946dd00-f823-11e9-907a-6f1d102fce45.png">

**Comment by juhana** [comment]
Sorry, forgot to publish the latest Haven version. The submodule should work now.

`Module` is not used anymore in the latest version (3.2.0) so I'm assuming there's some issue with the game still loading old files?

**Comment by michaelsharpe** [comment]
@juhana Awesome, thanks!

Any idea about the issue with the prompt being displayed now in the span of the previous output rather than the label of the input? Was that intentional?

**Comment by juhana** [comment]
Vorple uses its own prompt, so you'll have to disable the story's own prompt and enable Vorple's. That happens automatically at the start of game if you include any Vorple extension, but if you're doing something that causes the rule not to run you can run it manually with "follow the convert default prompt to Vorple prompt rule".

**Comment by michaelsharpe** [comment]
Beautiful. I hacked a solution together that filtered it out using your awesome new input and output filters, but it felt hacky.  Love the filters btw! I was thinking about integrating a websocket to let me take over control of the prompt from vorple with my players to simulate a conversation with them.  I was trying to figure out how to do this, but your filters make that so much simpler.  And the new file system really allows for some deep JS integrations with an API, even as far as having user accounts with saved cross platform states, etc.  Great job on the update!

Ok.  So I only have one more blocker to migrating my old system to the new Vorple, and getting the new features and persistent saving for my players.  I am now faced with this last error at startup which has arisen since my last version, and no idea where it is coming from:

<img width="930" alt="Screen Shot 2019-10-28 at 10 30 45 AM" src="https://user-images.githubusercontent.com/2397603/67687037-0826f380-f96e-11e9-8275-a76ca68cee45.png">

Oh, and I still don't seem to be able to run the `npm run compile` command to assemble the two emcripten resources for local development (unrelated to the above though).

Thanks for fielding all my questions!

**Comment by michaelsharpe** [comment]
A few additional notes on the above error.  It seems to be effecting all Vorple commands in my story.  None of them seem to run.  I stripped out everything but a room and Vorple, and it still appears.

I tried booting up another story, the demo Disenchantment Bay.  No vorple running aside from including it in the story along with the interpreter.  The vorple version is 3.2 installed from the downloads on the Vorple site and put into the templates and extensions folders.  Under this condition, the runtime error problem P48 is still showing up.

I am thinking this might be something in the latest Vorple update itself.  I'll try digging into your source, but as I can't compile the empscripten resources it might be difficult.

**Comment by juhana** [comment]
The error is most likely caused by interference by the previous version's control files. It'll probably work correctly if you try it in a different browser or in incognito mode. I'll try to see if I can find a way to do cleanup of the old files.

You don't need Emscripten anymore, the latest version doesn't use it. The build instructions are out of date so you can skip the build step.

**Comment by michaelsharpe** [comment]
Just tried it in incognito with no luck.  Also tried in another browser but still am seeing the error. I am not yet super familiar with your code base but let me know if I can help.

Great to know about not needing emscripten.  Much cleaner that way.  Glad to know I have all I need to start tweaking things locally.  Have been pondering on whether your engine could be made to communicate via javascript to a node environment rather than in a browser environment.

**Comment by michaelsharpe** [comment]
@juhana Do you have any more info on this? I have an update to story running live in production I want to push, and I integrated the latest Vorple into it.  However, if it break the JS content, I am going to have to revert back to what I using before.  All help is appreciated.

**Comment by juhana** [comment]
The only time I've seen this is when I7 fails to read or write the JavaScript evaluation files which are VpJSEval, VpJSRtrn and VpJSType. Other than that it's very hard to give any specific advice. If you have an example online somewhere, I can take a look.

**Comment by michaelsharpe** [comment]
@juhana I created an example repo.  

https://github.com/michaelsharpe/vorple-bug-example

Basically used one of the example stories that comes with Inform, added Vorple to the extensions folder and the templates folder, included it in the story with the interpreter, and then built it.  The story, at least on my machine, is producing the error.

<img width="1664" alt="Screen Shot 2019-11-01 at 11 32 26 AM" src="https://user-images.githubusercontent.com/2397603/68047337-5b18e780-fc9b-11e9-9985-55dfaf7a6393.png">

**Comment by juhana** [comment]
Thanks, I found the bug! It's to do with the interpreter detection. I'll fix it properly tomorrow, but as a temporary fix you can do this:

* Add `vorple.setInformVersion(7);` right before the `vorple.init()` line in Templates/Vorple/(manifest).txt
* Replace the detect interpreter's Vorple support rule starting from line 26 in Vorple.i7x with this:

```
This is the detect interpreter's Vorple support rule:
	now Vorple support is true.
```

This will disable Vorple detection so it'll break the game in offline interpreters, but it won't matter if you only have a Vorple version.

**Comment by michaelsharpe** [comment]
Beautiful! Thanks so much. I am super stoked to get saving activated for my players. And many thanks again for working to create such a JavaScript layer for inform. The inner workings of both inform, and the VM, are a huge mystery to me, being primarily a JS developer. So I really appreciate the work you have put in to this. Hopefully one day I can understand some of the deeper layers going on. 

I’ll implement this fix and let you know my success.

**Comment by juhana** [comment]
This is now properly fixed in the latest release (3.2.1).
